name: Hello World
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified        
      - name: python-dep
        run: |
          pip install six numpy wheel
          pip install keras_applications==1.0.6 --no-deps
          pip install keras_preprocessing==1.0.5 --no-deps
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.1.0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain patch unzip patch diffutils 
      - name: CI-Build
        shell: msys2 {0}
        run: |
          git clone https://github.com/Intel-tensorflow/tensorflow.git
          cd tensorflow
          git checkout r2.3-windows
          cp ../bazel.exe .
          cp ../WORKSPACE .
          python ./configure.py
          ./bazel.exe --output_base="./output" build --announce_rc --config=opt \
            --config=mkl \
            --action_env=PATH="./temp" \
            --define=no_tensorflow_py_deps=true \
            tensorflow/tools/pip_package:build_pip_package
          
          
